DatabaseOps/Database.py,sha256=ks2eoIdd4NJgc9PK0OPftXnJM7Bxnjq4ztHLuXnh_fw,198
DatabaseOps/DatabaseOperations.py,sha256=32CnC0gzevZ0SuD678oFCxKjJchfrBjZm-aSm_Th3Hw,9823
DatabaseOps/UserDefinedExceptions.py,sha256=8qf6NSmdEgOzLCWsS9DxqeNmYyTVpBVWHu19sO-n3zg,634
DatabaseOps/__init__.py,sha256=YFDkQPrQoEuXGM_QcVRKeYTh6vO5oUs5fwVKMN99awQ,35
pydbops-0.0.1.dist-info/LICENSE,sha256=JVWtqQQAXfEo3ICSfGf0topveOskoTIK5YCRj08vBqE,1094
pydbops-0.0.1.dist-info/METADATA,sha256=oei1X3vnSYJucFWBUJOJwgSq6RaPuVrhta68dNo2iis,540
pydbops-0.0.1.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
pydbops-0.0.1.dist-info/top_level.txt,sha256=csPsya1MJaASrrNbad_WxTFrvHD9G2s_wn08DA2Pujc,12
pydbops-0.0.1.dist-info/RECORD,,
